### ISSUE TITLE
libmirage 3.0.3 didn't work

### ISSUE THREAD

**Issue by xps2** [kepstin/image-id#6]
OS X 10.8.5
gcc-4.2.1-llvm(Apple)
architecture: x86_64
dependency library: from macports

| libmirage ver | image-id build | image-id work |
| --: | :-: | :-: |
| 2.0.0 | NG | NG |
| 2.1.0 | OK | OK |
| 2.1.1 | OK | NG |
| 3.0.3 | NG | NG |

**Comment by jesus2099** [comment]
@arx8, According to [github’s Markdown table syntax](https://guides.github.com/features/mastering-markdown/) :

```
libmirage ver | image-id build | image-id work
-------------:|:--------------:|:-------------:
2.0.0         | NG             | NG
2.1.0         | OK             | OK
2.1.1         | OK             | NG
3.0.3         | NG             | NG
```

gives :

| libmirage ver | image-id build | image-id work |
| --: | :-: | :-: |
| 2.0.0 | NG | NG |
| 2.1.0 | OK | OK |
| 2.1.1 | OK | NG |
| 3.0.3 | NG | NG |

:)

**Comment by xps2** [comment]
thanks @jesus2099 ! :smile: 

libmirage 2.1.1 + image-id error

```
$ ./image_id a.cue
Image ID 1.0
Copyright (c) 2013 Calvin Walton
**
ERROR:/Users/arx8/build/libmirage-2.1.1/src/libmirage/mirage-utils.c:654:mirage_helper_calculate_crc16: assertion failed: (data && crctab)
Abort trap: 6
```

**Comment by xps2** [comment]
libmirage 3.0.3 + image-id build error
(change `#include <mirage.h>` → `#include <mirage/mirage.h>`)

```
$ make
gcc -c -std=c99 -D_REENTRANT -I/usr/local/include/libmirage-3.0 -I/opt/local/include -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include  -g -Wall -O  image_id.c -o image_id.o
image_id.c: In function ‘process_disc’:
image_id.c:100: warning: implicit declaration of function ‘mirage_disc_get_mcn’
image_id.c:100: warning: comparison between pointer and integer
image_id.c:101: warning: passing argument 2 of ‘__builtin___strncpy_chk’ makes pointer from integer without a cast
image_id.c:101: warning: passing argument 2 of ‘__inline_strncpy_chk’ makes pointer from integer without a cast
gcc -L/usr/local/lib -L/opt/local/lib -ldiscid -lmirage -lgmodule-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl   image_id.o -o image_id
Undefined symbols for architecture x86_64:
  "_mirage_disc_get_mcn", referenced from:
      _main in image_id.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make: *** [image_id] Error 1
```

**Comment by xps2** [comment]
libmirage 2.1.0 + image-id work :smile: 

```
$ ./image_id a.cue 
Image ID 1.0
Copyright (c) 2013 Calvin Walton
Disc contains 1 sessions
Full TOC: 1 1 19614 150
MusicBrainz Disc ID: Vn5_OPhs5oHLPGwFictw9mly5CI-
FreeDB Disc ID: 02010301
MusicBrainz Submission URL: http://musicbrainz.org/cdtoc/attach?id=Vn5_OPhs5oHLPGwFictw9mly5CI-&tracks=1&toc=1+1+19614+150
ISRC Track 1: JPU901401758
```

**Comment by xps2** [comment]
libmirage 2.0.0 + image-id build error

```
$ make
gcc -c -std=c99 -D_REENTRANT -I/usr/local/include/libmirage -I/opt/local/include -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include  -g -Wall -O  image_id.c -o image_id.o
In file included from /usr/local/include/libmirage/mirage.h:35,
                 from image_id.c:24:
/usr/local/include/libmirage/mirage-contextual.h:25: error: redefinition of typedef ‘MirageDisc’
/usr/local/include/libmirage/mirage-context.h:25: error: previous declaration of ‘MirageDisc’ was here
In file included from /usr/local/include/libmirage/mirage.h:40,
                 from image_id.c:24:
/usr/local/include/libmirage/mirage-disc.h:82: error: redefinition of typedef ‘MirageDisc’
/usr/local/include/libmirage/mirage-contextual.h:25: error: previous declaration of ‘MirageDisc’ was here
In file included from /usr/local/include/libmirage/mirage.h:47,
                 from image_id.c:24:
/usr/local/include/libmirage/mirage-parser.h:25: error: redefinition of typedef ‘MirageDisc’
/usr/local/include/libmirage/mirage-disc.h:82: error: previous declaration of ‘MirageDisc’ was here
In file included from /usr/local/include/libmirage/mirage.h:49,
                 from image_id.c:24:
/usr/local/include/libmirage/mirage-sector.h:25: error: redefinition of typedef ‘MirageTrack’
/usr/local/include/libmirage/mirage-disc.h:26: error: previous declaration of ‘MirageTrack’ was here
/usr/local/include/libmirage/mirage-sector.h:79: error: redefinition of typedef ‘MirageSector’
/usr/local/include/libmirage/mirage-disc.h:27: error: previous declaration of ‘MirageSector’ was here
In file included from /usr/local/include/libmirage/mirage.h:50,
                 from image_id.c:24:
/usr/local/include/libmirage/mirage-session.h:25: error: redefinition of typedef ‘MirageTrack’
/usr/local/include/libmirage/mirage-sector.h:25: error: previous declaration of ‘MirageTrack’ was here
/usr/local/include/libmirage/mirage-session.h:26: error: redefinition of typedef ‘MirageLanguage’
/usr/local/include/libmirage/mirage-language.h:78: error: previous declaration of ‘MirageLanguage’ was here
/usr/local/include/libmirage/mirage-session.h:88: error: redefinition of typedef ‘MirageSession’
/usr/local/include/libmirage/mirage-disc.h:25: error: previous declaration of ‘MirageSession’ was here
In file included from /usr/local/include/libmirage/mirage.h:51,
                 from image_id.c:24:
/usr/local/include/libmirage/mirage-track.h:25: error: redefinition of typedef ‘MirageFragment’
/usr/local/include/libmirage/mirage-fragment.h:74: error: previous declaration of ‘MirageFragment’ was here
/usr/local/include/libmirage/mirage-track.h:26: error: redefinition of typedef ‘MirageIndex’
/usr/local/include/libmirage/mirage-index.h:37: error: previous declaration of ‘MirageIndex’ was here
/usr/local/include/libmirage/mirage-track.h:27: error: redefinition of typedef ‘MirageLanguage’
/usr/local/include/libmirage/mirage-session.h:26: error: previous declaration of ‘MirageLanguage’ was here
/usr/local/include/libmirage/mirage-track.h:28: error: redefinition of typedef ‘MirageSector’
/usr/local/include/libmirage/mirage-sector.h:79: error: previous declaration of ‘MirageSector’ was here
/usr/local/include/libmirage/mirage-track.h:77: error: redefinition of typedef ‘MirageTrackModes’
/usr/local/include/libmirage/mirage-sector.h:26: error: previous declaration of ‘MirageTrackModes’ was here
/usr/local/include/libmirage/mirage-track.h:130: error: redefinition of typedef ‘MirageTrack’
/usr/local/include/libmirage/mirage-session.h:25: error: previous declaration of ‘MirageTrack’ was here
In file included from /usr/local/include/libmirage/mirage.h:52,
                 from image_id.c:24:
/usr/local/include/libmirage/mirage-utils.h:25: error: redefinition of typedef ‘MirageTrackModes’
/usr/local/include/libmirage/mirage-track.h:77: error: previous declaration of ‘MirageTrackModes’ was here
make: *** [image_id.o] Error 1
```

**Comment by kepstin** [comment]
Because libmirage changes API, image-id only works with one version of libmirage.

image-id '1.0.1' only works with libmirage 2.1

I am now updating image-id so it works with libmirage 3.0. When I make this change, image-id will not work with libmirage 2.1 or earlier.

**Comment by kepstin** [comment]
OK, I've made a new release image-id 2.0.0 which works with libmirage 3.0.

This new release does not work with older versions of libmirage.

Please download it at https://github.com/kepstin/image-id/releases/tag/v2.0.0

**Comment by JonnyJD** [comment]
The Makefile probably also needs an update.

With a more complex build system (cmake?) it might be possible to support multiple libmirage versions with one codebase. I am not sure if that is worth the effort, though. The underlying problem really is the unstable libmirage api.

**Comment by kepstin** [comment]
Oh, of course the Makefile also needs an update... Why didn't I bother to look at that. It won't actually break anything, but it may mislead people into believing it'll work with the older libmirage release.

The changes between libmirage 2.1 and 3.0 were fairly minimal; the difference was only that the MCN code was moved from the disc to the session. Yes, with a more advanced build system I could detect that and use an `ifdef` in the code to select it.

(I'm not a cmake fan, though)

I cannot support libmirage ≤2.0 that way, the changes are too big.

**Comment by kepstin** [comment]
OK, I decided to make the buildsystem use autotools; the new release 2.1.0 can switch between libmirage 2.1 and 3.0 (you need to re-run `./configure` to change it)

**Comment by JonnyJD** [comment]
Great. Thanks.

**Comment by xps2** [comment]
Thanks! :smile: 

OS X 10.8.5
CC: Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
GCC: gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
architecture: x86_64
dependency library: from macports

| libmirage ver | image-id work |
| --: | :-: |
| 2.1.0 | OK |
| 2.1.1 | OK |
| 3.0.0 | OK |
| 3.0.1 | OK |
| 3.0.2 | OK |
| 3.0.3 | OK |

libmirage patch(mac): https://github.com/xps2mb/libmirage-patch
